vich_uploader:
    db_driver: orm
    mappings:
        aircraft_images:
            uri_prefix: /uploads/aircrafts
            upload_destination: '%kernel.project_dir%/public/uploads/aircrafts'
            namer: app.custom_unique_namer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
