version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: air_charter_db
      MYSQL_USER: symfonyuser
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
