# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    aircraft_upload_dir: '%env(resolve:AIRCRAFT_UPLOAD_DIR)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\OpenApi\CustomOpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments:
            $decorated: '@App\OpenApi\CustomOpenApiFactory.inner'
        autowire: true
        autoconfigure: false

    Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTAuthenticator:
        autowire: true
        autoconfigure: true
        public: true
    
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: 'kernel.event_listener', event: 'lexik_jwt_authentication.on_authentication_success', method: 'onAuthenticationSuccess' }

    App\DataPersister\UserDataPersister:
        decorates: 'api_platform.doctrine.orm.state.persist_processor'
        arguments:
            $decorated: '@App\DataPersister\UserDataPersister.inner'
        
    app.custom_unique_namer:
        class: App\Service\Namer\CustomUniqueNamer
        tags:
            - { name: vich_uploader.namer }

    app.custom_unique_namer.aircraft_images:
        parent: app.custom_unique_namer
        public: true
    
    App\State\BookingProcessor:
        arguments:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'
        tags: ['api_platform.state_processor']

